# cd.yml


name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/myapp
            TAG=${{ github.event.workflow_run.head_sha }}

            echo "Deploying: $IMAGE:$TAG"

            sudo apt-get update -y
            sudo apt-get install -y docker.io apache2

            sudo docker rm -f myapp || true

            sudo docker pull $IMAGE:$TAG

            sudo docker run -d --name myapp -p 8080:80 $IMAGE:$TAG

            sudo systemctl restart apache2



# ci.yml

name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_sha: ${{ steps.sha_step.outputs.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: Get SHA for artifact
        id: sha_step
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image (sha + latest)
        env:
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/myapp
          TAG: ${{ steps.sha_step.outputs.sha }}
        run: |
          docker build -t $IMAGE:latest -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
